### ISSUE TITLE
If the keys are not set, all other operations fail

### ISSUE THREAD

**Issue by andypiper** [CruiseDevice/twweet-cli#14]
On first run, if there is no consumer key or OAuth token, the app should prompt to create them. Until this happens, all get and twweet operations will fail with Twitter API errors.

**Comment by ritiek** [comment]
I'd like to help.

How about reading the credentials from a (config) file instead of hard coding them in the code itself? The script will read the credentials from the config file and tell the user to set them if not set already.

**Comment by ediamondscience** [comment]
I'd like to help as well. 

I think that we can just have each key stored as a line on a text file. We can have the file start out early and have the user re-enter their keys if authentication through the get_api method fails. Should just be adding a try-except statement to that method and having the except clause call another method that has the user re-enter their keys. 

Should look something like this, but I haven't gotten all my bugs out yet:

```

#set up a list of keys from key file
cfglist = ['' for _ in range(4)] 
with open('./keys.txt') as f:
    i=0
    for line in f:
        line=line.strip() 
        cfglist[i]=line


cfg = {
   "consumer_key"        : cfglist[0],
   "consumer_secret"     : cfglist[1],
   "access_token"        : cfglist[2],
   "access_token_secret" : cfglist[3]
   }


def get_user_keys():
    #get keys from user input 
    cons_key = raw_input("Please enter your consumer key: ")
    cons_sec = raw_input("Please enter your consumer secret: ")
    acc_token = raw_input("Please enter your access token: ")
    acc_token_sec = raw_input("Please enter your access token secret: ")

    #reset dict values for cfg
    cfg = {
       "consumer_key"        : cons_key,
       "consumer_secret"     : cons_sec,
       "access_token"        : acc_token,
       "access_token_secret" : acc_token_sec
       }

    #finally save keys to text file
    with open('./keys.txt', 'a') as keyfile:
        keyfile.write(conskey+'\n')
        keyfile.write(cons_sec+'\n')
        keyfile.write(acc_token+'\n')
        keyfile.write(acc_token_sec+'\n') 

def get_api(cfg):
    #Twitter only allows access to a users most recent 3240 tweets with this method

    authenticated=False
    while authenticated!=True:
        try:
            auth = tweepy.OAuthHandler(cfg['consumer_key'], cfg['consumer_secret'])
            auth.set_access_token(cfg['access_token'], cfg['access_token_secret'])
            authenticated=True
        except:
            get_usr_keys()
    return tweepy.API(auth)

```

I'm still having problems getting the base code without these changes to run though, may take some time before I can fix the base version to run on my machine. 

***EDIT***

I think I've got things working now, but I managed to do it by refactoring the code to work in python 3.6.1. Is there any special reason this is being written in python 2.7?

**Comment by CruiseDevice** [comment]
@ritiek @ediamondscience @andypiper  I think it is better to keep the keys in other file than to store in the database. User must be prompted to provide his/her key at the time of setup(first time installation). It is obvious app will crash, if keys are not provided.

**Comment by CruiseDevice** [comment]
Right now the setup file is of no use, because we are using the twweet_cli.py file directly for installation. There must be changes made to setup file such that installation happens by running setup.py and not twweet_cli.py

**Comment by 0x006E** [comment]
I think I could modify setup.py for custom build commands when running install.. It will ask for All the consumer secrets

**Comment by mblissmer** [comment]
Doesn't the main twweet_cli.py do this now?

```
def createCreds():
    ck = raw_input('Enter your Consumer Key: ').strip()
    cs = raw_input('Enter your Consumer Secret: ').strip()
    at = raw_input('Enter your Access Token: ').strip()
    ats = raw_input('Enter your Access Token Secret: ').strip()
    jsondata= {"consumer_key": ck,
    "consumer_secret": cs,
    "access_token": at,
    "access_token_secret": ats}
    with open("data/creds.json", "w") as outfile:
        json.dump(jsondata, outfile)
```

**Comment by CruiseDevice** [comment]
Yes i think setup.py should be removed. As it is of no use right now. twweet_cli.py does the same work as setup.py was intended to do. I will remove this in my next pr.

**Comment by 0x006E** [comment]
If the setup file is removed then we would have to run py file directly. But with the setup. We only wan to run twweet-cli from the terminal

**Comment by 0x006E** [comment]
This issue is fixed and should be closed.
