### ISSUE TITLE
Python3.6 refactor?

### ISSUE THREAD

**Issue by ediamondscience** [CruiseDevice/twweet-cli#15]
I mentioned this in #14 but this is probably a big enough proposition to warrant it's own thread. I'm a little confused as to why this project is being written in legacy code. I've refactored and tested twweet-cli.py and it seems to work just fine (I didn't test every function but it is still able to tweet and read tweets). Please let me know what you think and if you'd like to go through with a refactor.

**Comment by moyamanuel** [comment]
Although Python 2 will still be supported until 2020, I do agree it should be ported over to Python 3  in order to keep it up to modern standards.

**Comment by CruiseDevice** [comment]
@ediamondscience Yes this project can be refactored to python 3. I don't think there should be many changes to make.

**Comment by csdeshpande19** [comment]
Can you please assign me this issue. I'm a newbie but I'll try my best.
