### ISSUE TITLE
Add nice formatting for timeline/searched tweets?

### ISSUE THREAD

**Issue by ediamondscience** [CruiseDevice/twweet-cli#24]
Hey all, I was wondering if someone might take on having some kind of formatting settings or adjustments to make viewing your timeline or your own tweets easier to read. Currently everything is just output as a large list of tweets with attributes showing. Perhaps we could have some sort of filter function to pair this down and get it into a more readable state? It would be nice if it took parameters so that the user could have some settings regarding how things are displayed.

**Comment by mblissmer** [comment]
I was actually just messing with this, this last weekend. I hadn't thought of there being options for display, but I'm sure I could build some customization options into this. 

Happy to take a shot at this one!

**Comment by CruiseDevice** [comment]
I tried displaying timeline/searched result in json format. This can be formatted in much clean way, as it must only display tweets, likes and retweets from timeline. For now it shows a lot of information which i think is unnecessary.
