### ISSUE TITLE
After command, return to main menu

### ISSUE THREAD

**Issue by mblissmer** [CruiseDevice/twweet-cli#25]
It would be nice to stay in the program until you tell it you want to quit. Basically after doing a thing ("show my tweets" etc), it should drop you back to the main menu to make another selection. Also if we're doing that, a "quit" option should be added too!

I'm happy to do this one if you guys don't already have it in the works!

**Comment by blavejr** [comment]
I have added this in my fork, I have also put in a pull request so I think it should be merged soon.
I simply added a decorator around main function that recalls main after main is done running, Maybe later we should add some kind of loop though so we don't have to re-initialise the entire script every time.

**Comment by 0x006E** [comment]
Gd idea guys. Drop a PR when done.

**Comment by mblissmer** [comment]
@nithinswarrier , it sounds like @blavejr has one waiting for you. :)

My thinking was to put the main logic in a while loop, but I haven't messed with decorators very much, so that may be just as good if not better.

**Comment by 0x006E** [comment]
But @blavejr 's code has some problems. Look at his fork. It now also uses SqliteDB instead of JSON which was merged to master branch in PR #22 . He has to update his code. And also his repo has some unwanted files like .xml and some db files. he has to remove those before merging it to the master branch

**Comment by mblissmer** [comment]
Ah, yes, I see that now. (Sorry, still new to github). I'll wait for him to do his thing. I'm around as a backup if needed for any reason for this issue.

**Comment by 0x006E** [comment]
You could make up a new Idea and open a new issue for that. Lets leave this topic to him. I will look at his work

**Comment by blavejr** [comment]
Hi guys sorry I haven't been up to date, I will look to fixing these issues during the weekend.
