### ISSUE TITLE
Save tweets of users and tweets of particular hashtag in separate folder.

### ISSUE THREAD

**Issue by CruiseDevice** [CruiseDevice/twweet-cli#29]
After getting tweets of user or getting tweets of particular hashtag, a csv file is created for each. These files are directly saved in the root of the project directory. There must be a separate directory for these files and they must be ignored by github.

**Comment by Griffintaur** [comment]
@CruiseDevice, I would love to take up this if it still open

**Comment by 0x006E** [comment]
@Griffintaur. Its still open. After doing it drop a PR :) Gd luck on your work. If any problem or suggestion join the gitter chat which mentioned in the Readme.md

**Comment by CruiseDevice** [comment]
fixed in PR #33
