### ISSUE TITLE
Make class

### ISSUE THREAD

**Issue by blavejr** [CruiseDevice/twweet-cli#36]
I suggest we put the code in a class, in case we want to add other functionality later we can have "add-ons" separated from the core programme. plus it's a little more organised that way.

**Comment by thakkardharmik** [comment]
@CruiseDevice I would like to give it a try. Please suggest me how to get started.

**Comment by janvi-palan** [comment]
Hello,

Is this still open? Can I start working on this?

**Comment by 0x006E** [comment]
Yah!. Its still open. Drop a PR. Any doubts or suggestions can be cleared by joining the gitter group.
Good luck for your good work anyway

**Comment by thakkardharmik** [comment]
@janvi-palan Shall we do it together?

**Comment by thakkardharmik** [comment]
@blavejr @nithinswarrier Please review the code. We need to make changes to setup.py in case the code looks fine to you guys. Also I will need some help to test the code. Thanks.

**Comment by againafter10** [comment]
@thakkardharmik  I can help you test it,Let me know if this is still wanted?

**Comment by 0x006E** [comment]
@againafter10 You can do it. Gud luck for the contribution

**Comment by sai10** [comment]
I want to give it a try . Is it still open.

**Comment by 0x006E** [comment]
This issue has been fixed in PR #50 . Please close this. @sai10 you can check the setup.py and implement the needed changes for the program to work. Drop a PR if you are doing this.

**Comment by CruiseDevice** [comment]
somebody please create the new issue for setup.py.
