### ISSUE TITLE
setup.py: cannot create data dir

### ISSUE THREAD

**Issue by thakkardharmik** [CruiseDevice/twweet-cli#37]
User:twweet-cli $ sudo python setup.py install
running install
Creating Data Directories...
Cannot create data dir the installation cannot continue..

**Comment by 0x006E** [comment]
Once created the folder has to be created. I will change the setup.py

**Comment by CruiseDevice** [comment]
@thakkardharmik Check if the directory is created. This happens if you already have data directory created.

**Comment by thakkardharmik** [comment]
@CruiseDevice Please provide me access to commit to the master branch. I am adding a fix for this issue to check if the data dir exists for Python 3.X.
