### ISSUE TITLE
Parsing the Follower List's  Json

### ISSUE THREAD

**Issue by Griffintaur** [CruiseDevice/twweet-cli#39]
It seems when the follower list is queried, it just dumped the whole JSON data without parsing.
This doesn't seem nice.

**Comment by blavejr** [comment]
I can parse it.

**Comment by CruiseDevice** [comment]
anyone working on this?

**Comment by blavejr** [comment]
I'll do it tonight.

**Comment by Griffintaur** [comment]
if @blavejr is busy, I can take it up too.

**Comment by 0x006E** [comment]
You both can do. Whose PR is good and the first one Wins. !!!

**Comment by blavejr** [comment]
Yeah bro just do it, got caught up

**Comment by Griffintaur** [comment]
PR #44

**Comment by CruiseDevice** [comment]
#44 fixes this
