### ISSUE TITLE
Add contributing section in the README

### ISSUE THREAD

**Issue by Griffintaur** [CruiseDevice/twweet-cli#45]
1. add contributing section in the README with following subsections
  - Features we want or things to do
  - Things that have been done

**Comment by dibyasonu** [comment]
Is this still open. I am completely new to open source and if possible i hope to make it my first contribution on github on any public repos, Plus it would help me for hacktoberfest event

**Comment by 0x006E** [comment]
Yah!. Its open. Drop a PR when done!!

**Comment by dibyasonu** [comment]
I have some doubts regarding the subsection "Features we want or things to do".  Can u mention what details u want in that . i have joined the gitter room if possible u can provide some details regarding the above topic in the chat..

**Comment by 0x006E** [comment]
Leave that one. Its future for now. Please do the rest and sent a PR.. You can make it in an another commit or push.

**Comment by aitoehigie** [comment]
I have sent in a PR addressing this. Kindly check

**Comment by 0x006E** [comment]
@aitoehigie Where is the PR?

**Comment by dibyasonu** [comment]
@CruiseDevice I have sent a PR for #45. Please let me know any changes u want to get done.

**Comment by 0x006E** [comment]
Sorry @aitoehigie Please check on some other issue. Or find us a bug. We will be greatful. Gd lck for your opensource contribution. :+1:

**Comment by 0x006E** [comment]
Please close this issue. Its fixed

**Comment by aitoehigie** [comment]
Already closed.

**Comment by 0x006E** [comment]
@CruiseDevice Please close the issue
