### ISSUE TITLE
Broken setup.py - [Fix Needed]

### ISSUE THREAD

**Issue by 0x006E** [CruiseDevice/twweet-cli#51]
The following PR(s) broke the setup.py:
[x] #50 - Modularizing the code.
So there should be changes needed to fix this. Now the program contains 4 files instead of 1 file.And the old file twweet_cli.py should be removed as there is no need of it now.

**Comment by kalbhor** [comment]
Can I take this?

**Comment by kalbhor** [comment]
Do I just have to remove the ```twweet_cli.py``` file? What other changes need to be made?

**Comment by 0x006E** [comment]
Changes you should make is:
1. Delete the twweet_cli.py
2.Change the setup.py so that all other py files and config install. 
Thats the change that is required. Gd lck anyway. Drop a PR when done
