### ISSUE TITLE
Fastest way to rebuild the project without installing it again.

### ISSUE THREAD

**Issue by CruiseDevice** [CruiseDevice/twweet-cli#61]

**Comment by Pacnova** [comment]
Hello

**Comment by smartinov** [comment]
@CruiseDevice hi, what do you mean the fastest way to rebuild the project?

Perhaps it could be done with dokerization?

**Comment by CruiseDevice** [comment]
Each time you have to delete the application and install it again for debugging. Installing it again requires setting up the api keys again, which is time consuming. So looking for a way where user don't have to repeat this mundane process of installing and setting keys again and again, where user can build the application by entering few commands(possibly one or two) and the keys should be automatically set. This is just one idea, i am sure there must be more optimized method for building the project.

**Comment by smartinov** [comment]
Alright, what about that we make a file like .cruisedevice in the home folder  of the user, which we have like a configuration provider which looks and persists the credentials in that folder, that persists after installation?

**Comment by smartinov** [comment]
Also, have you thought about porting this to go? It would have a good benefit of having a pre-build executable files and everything!

**Comment by CruiseDevice** [comment]
a configuration file would be awesome, it just need to be gitignored. We previously use to have a file where all the api credentials were stored. Porting it to go? Well i never tried go, so never thought of it.

@nithinswarrier  What do you think about porting it to go? If you have any views on this issue, you can share.

**Comment by 0x006E** [comment]
I surely don't know about Go. With my previous experience with Go, I think its actually a good idea.

**Comment by smartinov** [comment]
I'm actually programming full time in GO, so we might think about doing a nice thing there!

**Comment by 0x006E** [comment]
Anyway its an opensource project. So it might be nice!

**Comment by banks117** [comment]
@CruiseDevice Would this meet your needs?
https://github.com/CruiseDevice/twweet-cli/pull/75

**Comment by CruiseDevice** [comment]
Feels like this has been resolved. So closing this issue. Thanks @brandonmbanks :tada:
