### ISSUE TITLE
Add ascii twweet-cli banner at the top in command line.

### ISSUE THREAD

**Issue by CruiseDevice** [CruiseDevice/twweet-cli#62]

**Comment by pulkitmaloo** [comment]
I made this one from <a href="http://www.network-science.de/ascii/">here</a> 
```
#######                                                         
   #    #    # #    # ###### ###### #####        ####  #      # 
   #    #    # #    # #      #        #         #    # #      # 
   #    #    # #    # #####  #####    #   ##### #      #      # 
   #    # ## # # ## # #      #        #         #      #      # 
   #    ##  ## ##  ## #      #        #         #    # #      # 
   #    #    # #    # ###### ######   #          ####  ###### # 
```
 Any other ideas?

**Comment by CruiseDevice** [comment]
Yours looks nice. How about this

`
  __                                  __                   .__  .__ 
_/  |___  _  ____  _  __ ____   _____/  |_            ____ |  | |__|
\   __\ \/ \/ /\ \/ \/ // __ \_/ __ \   __\  ______ _/ ___\|  | |  |
 |  |  \     /  \     /\  ___/\  ___/|  |   /_____/ \  \___|  |_|  |
 |__|   \/\_/    \/\_/  \___  >\___  >__|            \___  >____/__|
                            \/     \/                    \/         
`

**Comment by CruiseDevice** [comment]
How about something with graffiti font?

**Comment by CruiseDevice** [comment]
Use these settings on the same site
`Font: graffiti   Reflection: no   Adjustment: left   Stretch: no      Width: 80	 Text: tweet-cli`

**Comment by romwhite** [comment]
I  see a "merged" label but under "Issues" this is still listed as "up for grabs"? I'm happy to contribute if work is still needed.
