### ISSUE TITLE
Windows instructions

### ISSUE THREAD

**Issue by cskinner74** [CruiseDevice/twweet-cli#66]
I know this is knit-picky, but the Windows instructions for running the setup.py script in the ReadMe are:

> For Windows users: `$ sudo python setup.py install`
sudo should be left out since it's not a Windows command.

Also, it's been a while since I've used python on Window, so correct me if I'm wrong, but when running pip, I believe they would need to type `python -m pip install tweepy`
I can verify this one later tonight.

**Comment by CruiseDevice** [comment]
I am not a windows person, but i guess yes. For installing any python package you can do `python -m pip install <package_name>`. But `$ sudo python setup.py install` is for installing this application in your system.

**Comment by cskinner74** [comment]
True, but 'sudo' should still be left out since it's a *NIX command

**Comment by blackbird71SR** [comment]
For windows:
`python setup.py install` should be used. If you use `sudo python setup.py install`, it will not work.

**Comment by CruiseDevice** [comment]
Looks like this has been fixed so closing it. Thanks
