### ISSUE TITLE
What are the plans for the future?

### ISSUE THREAD

**Issue by sheepster1** [CruiseDevice/twweet-cli#72]
I messed around with the api some time ago, maybe i can help..

**Comment by 0x006E** [comment]
So.. What is you plan for the future of this CLI? Tell us.

**Comment by CruiseDevice** [comment]
As of now there is not much going on my mind about this project. If you have anything to share about it you are welcome.

**Comment by pulkitmaloo** [comment]
I think [shallow-backup](https://github.com/alichtman/shallow-backup) has done a great job at the interface. Maybe we can improve the interface taking inspiration from them?
