### ISSUE TITLE
Difference in key names between ConfigReader and setup

### ISSUE THREAD

**Issue by weijuly** [CruiseDevice/twweet-cli#73]
There is a difference between the key names used in the `config.yml` file created via [`setup.py`](https://github.com/CruiseDevice/twweet-cli/blob/master/setup.py) (key names are `Tweets` and `HashTag` here) and in the [`ConfigReader`](https://github.com/CruiseDevice/twweet-cli/blob/master/twweet_cli/config/ConfigReader.py) (key names are `tweets` and `hashtag` here). This results in:

```
  File "/Users/gganesan/mac/code/pub-github/weijuly/twweet-cli/twweet_cli/config/ConfigReader.py", line 18, in __init__
    ConfigurationReader.__tweets = cfg['tweets']
KeyError: 'tweets'
```
Let me know if I can issue a PR to resolve this. 

PS: I'm very new to open source contribution - it'd be great to get some guidance and mentorship 😄

**Comment by 0x006E** [comment]
Thanks for the PR. Will merge 👍
