### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CruiseDevice** [CruiseDevice/twweet-cli#9]

**Comment by moyamanuel** [comment]
I can write the documentation in both English and Spanish. Do you mind creating a wiki page for the project? @CruiseDevice

**Comment by CruiseDevice** [comment]
@moyamanuel  No problem with the wiki page. But the instructions are already in README.md. So what we gonna put in wiki?

**Comment by moyamanuel** [comment]
Right, I noticed the instructions were already listed in the README.md. I thought there was more documentation to write due to the fact that this issue was opened up

**Comment by CruiseDevice** [comment]
@moyamanuel No problem.
